nusim:
  ros__parameters:
    slip_fraction: 0.0
    input_noise: 0.0
    lidar_variance: 0.001
    basic_sensor_variance: 0.0
    max_range: 5.0
    x0: 0.0
    y0: 0.0
    theta0: 0.0
    obstacles/x: [0.5]
    obstacles/y: [0.5]
    obstacles/r: 0.038


