nusim:
  ros__parameters:
    slip_fraction: 0.0
    input_noise: 0.0
    basic_sensor_variance: 0.001
    max_range: 5.0
    x0: 0.0
    y0: 0.0
    theta0: 0.0
    obstacles/x: [1.0, -1.0, 0.0, -1.0, 1.0, 0.0]
    obstacles/y: [1.0, 1.0, 1.0, -1.0, -1.0, 1.0]
    obstacles/r: 0.038


